vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/img
            upload_destination: '%kernel.project_dir%/public/images/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
