<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '4d4f45e6c79aecc349cffbf6ffdfd857',
  'DATABASE_URL' => 'mysql://x1v7euvf_rene:JxLQFt2R1lw^tAH2@127.0.0.1:3306/x1v7euvf_rene?serverVersion=5.7.24&charset=utf8mb4',
);
