<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '4d4f45e6c79aecc349cffbf6ffdfd857',
  'DATABASE_URL' => 'mysql://root:root@127.0.0.1:3306/rene?serverVersion=5.7.24&charset=utf8mb4',
);
