<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerETkrhAt\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerETkrhAt/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerETkrhAt.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerETkrhAt\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerETkrhAt\App_KernelEnvDebugContainer([
    'container.build_hash' => 'ETkrhAt',
    'container.build_id' => 'b3b07625',
    'container.build_time' => 1700398764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerETkrhAt');
