<?php

namespace ContainerHDsK3D8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImpressumControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImpressumController' shared autowired service.
     *
     * @return \App\Controller\ImpressumController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ImpressumController.php';

        $container->services['App\\Controller\\ImpressumController'] = $instance = new \App\Controller\ImpressumController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\ImpressumController', $container));

        return $instance;
    }
}
