<?php

namespace ContainerRsoWyOW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeadInfoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HeadInfoRepository' shared autowired service.
     *
     * @return \App\Repository\HeadInfoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HeadInfoRepository'] = new \App\Repository\HeadInfoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
