<?php

namespace Container6575u65;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLebenslaufRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LebenslaufRepository' shared autowired service.
     *
     * @return \App\Repository\LebenslaufRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LebenslaufRepository'] = new \App\Repository\LebenslaufRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
