<?php

namespace Container89xPDi1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CsvRepository' shared autowired service.
     *
     * @return \App\Repository\CsvRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CsvRepository'] = new \App\Repository\CsvRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
