<?php

namespace Container89xPDi1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjekteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProjekteController' shared autowired service.
     *
     * @return \App\Controller\ProjekteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProjekteController'] = $instance = new \App\Controller\ProjekteController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ProjekteController', $container));

        return $instance;
    }
}
