<?php

namespace Container89xPDi1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SocialController' shared autowired service.
     *
     * @return \App\Controller\SocialController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SocialController'] = $instance = new \App\Controller\SocialController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\SocialController', $container));

        return $instance;
    }
}
