<?php

namespace ContainerIxEjRpf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZpMBXSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZpMBXS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZpMBXS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'tr' => ['privates', 'App\\Repository\\TexteRepository', 'getTexteRepositoryService', true],
        ], [
            'doctrine' => '?',
            'tr' => 'App\\Repository\\TexteRepository',
        ]);
    }
}
