<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container89xPDi1\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container89xPDi1/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container89xPDi1.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container89xPDi1\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container89xPDi1\App_KernelProdContainer([
    'container.build_hash' => '89xPDi1',
    'container.build_id' => '7f9a5b2b',
    'container.build_time' => 1700399136,
], __DIR__.\DIRECTORY_SEPARATOR.'Container89xPDi1');
