<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6575u65\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6575u65/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container6575u65.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container6575u65\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container6575u65\App_KernelProdContainer([
    'container.build_hash' => '6575u65',
    'container.build_id' => 'ff9453c0',
    'container.build_time' => 1686245052,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6575u65');
