<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2oHg2Le\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2oHg2Le/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2oHg2Le.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2oHg2Le\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2oHg2Le\App_KernelDevDebugContainer([
    'container.build_hash' => '2oHg2Le',
    'container.build_id' => '02ea9755',
    'container.build_time' => 1700401864,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2oHg2Le');
