<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Gx6hv2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Gx6hv2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Gx6hv2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Gx6hv2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0Gx6hv2\App_KernelDevDebugContainer([
    'container.build_hash' => '0Gx6hv2',
    'container.build_id' => '2190349e',
    'container.build_time' => 1687799224,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Gx6hv2');
