<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXSBNMLT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXSBNMLT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXSBNMLT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXSBNMLT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXSBNMLT\App_KernelDevDebugContainer([
    'container.build_hash' => 'XSBNMLT',
    'container.build_id' => 'ff6e5937',
    'container.build_time' => 1686251441,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXSBNMLT');
