<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Csv extends \App\Entity\Csv implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'firma', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'beschreibung', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'datebegin', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'dateend', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'rel'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'firma', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'beschreibung', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'datebegin', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'dateend', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'enable', '' . "\0" . 'App\\Entity\\Csv' . "\0" . 'rel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Csv $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirma(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirma', []);

        return parent::getFirma();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirma(string $firma): \App\Entity\Csv
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirma', [$firma]);

        return parent::setFirma($firma);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeschreibung(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeschreibung', []);

        return parent::getBeschreibung();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeschreibung(string $beschreibung): \App\Entity\Csv
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeschreibung', [$beschreibung]);

        return parent::setBeschreibung($beschreibung);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatebegin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatebegin', []);

        return parent::getDatebegin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatebegin(string $datebegin): \App\Entity\Csv
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatebegin', [$datebegin]);

        return parent::setDatebegin($datebegin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateend(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateend', []);

        return parent::getDateend();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateend(string $dateend): \App\Entity\Csv
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateend', [$dateend]);

        return parent::setDateend($dateend);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnable', []);

        return parent::getEnable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnable(bool $enable): \App\Entity\Csv
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnable', [$enable]);

        return parent::setEnable($enable);
    }

    /**
     * {@inheritDoc}
     */
    public function getRel(): ?\App\Entity\Berufsweg
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRel', []);

        return parent::getRel();
    }

    /**
     * {@inheritDoc}
     */
    public function setRel(?\App\Entity\Berufsweg $rel): \App\Entity\Csv
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRel', [$rel]);

        return parent::setRel($rel);
    }

}
