<?php

namespace Container0Gx6hv2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UgVKvM8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UgVKvM8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UgVKvM8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'imp' => ['privates', 'App\\Repository\\ImpressumRepository', 'getImpressumRepositoryService', true],
        ], [
            'doctrine' => '?',
            'imp' => 'App\\Repository\\ImpressumRepository',
        ]);
    }
}
